// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_5zWnK6ZB5mKu0Z0dxjJ8vHR64lrH8FM',
    appId: '1:874879212582:web:b0743f8c018e12ed40dae7',
    messagingSenderId: '874879212582',
    projectId: 'flutterprlogin',
    authDomain: 'flutterprlogin.firebaseapp.com',
    storageBucket: 'flutterprlogin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY8rVzE2MrtVoCM-gpCbdvXQ4mmNs9mok',
    appId: '1:874879212582:android:4f5277f39285e70440dae7',
    messagingSenderId: '874879212582',
    projectId: 'flutterprlogin',
    storageBucket: 'flutterprlogin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN9zs1J7OpgE7x1kI3YhUHYRn6gvHcQIc',
    appId: '1:874879212582:ios:dc2dd7e4cc6f79c440dae7',
    messagingSenderId: '874879212582',
    projectId: 'flutterprlogin',
    storageBucket: 'flutterprlogin.appspot.com',
    iosBundleId: 'com.example.userCreateLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN9zs1J7OpgE7x1kI3YhUHYRn6gvHcQIc',
    appId: '1:874879212582:ios:fbc7b9621560ec6240dae7',
    messagingSenderId: '874879212582',
    projectId: 'flutterprlogin',
    storageBucket: 'flutterprlogin.appspot.com',
    iosBundleId: 'com.example.userCreateLogin.RunnerTests',
  );
}
